import 'package:booking/models/place.dart';
import 'package:booking/style.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

List<Place> listOfPlaces = [
  Place(
      photo: "assets/images/foto1.jpg",
      name: "Hotel Transilvânia",
      // star1: FaIcon(FontAwesomeIcons.solidStar),
      // star2: FaIcon(FontAwesomeIcons.solidStar),
      // star3: FaIcon(FontAwesomeIcons.solidStar),
      // star4: FaIcon(FontAwesomeIcons.solidStar),
      // star5: FaIcon(FontAwesomeIcons.solidStar),
      points: 9.1,
      extra1: FaIcon(FontAwesomeIcons.snowflake),
      text1: "Ambiente climatizado",
      extra2: FaIcon(FontAwesomeIcons.mugHot),
      text2: "Refeições inclusas",
      extra3: FaIcon(FontAwesomeIcons.bus),
      text3: "Transporte Aeroporto / Hotel",
      description: "Quarto Deluxe com cama King-Size",
      daily: 4,
      price: "2.790,00"),
  Place(
      photo: "assets/images/foto2.jpg",
      name: "Hotel Malibu",
      points: 9.6,
      extra1: FaIcon(FontAwesomeIcons.conciergeBell),
      text1: "Serviço de quarto",
      extra2: FaIcon(FontAwesomeIcons.mugHot),
      text2: "Refeições inclusas",
      extra3: FaIcon(FontAwesomeIcons.wifi),
      text3: "Wi-Fi gratuito",
      description: "Excelente culinária típica e uma linda vista do Mar",
      daily: 4,
      oldPrice: "1.780,00",
      redColor: oldPriceTheme,
      price: "1.456,00",
      greenColor: priceTheme,
      app: "Só no APP"),
  Place(
      photo: "assets/images/foto3.jpg",
      name: "Hotel Porto Mauá",
      points: 8.9,
      extra1: FaIcon(FontAwesomeIcons.snowflake),
      text1: "Ambiente climatizado",
      extra2: FaIcon(FontAwesomeIcons.mugHot),
      text2: "Refeições inclusas",
      extra3: FaIcon(FontAwesomeIcons.swimmingPool),
      text3: "Área de natação",
      description: "Quarto Deluxe com cama King-Size",
      daily: 4,
      price: "2.670,00"),
  Place(
      photo: "assets/images/foto4.jpg",
      name: "Hotel Recanto da Paz",
      points: 9.0,
      extra1: FaIcon(FontAwesomeIcons.snowflake),
      text1: "Ambiente climatizado",
      extra2: FaIcon(FontAwesomeIcons.mugHot),
      text2: "Refeições inclusas",
      extra3: FaIcon(FontAwesomeIcons.bus),
      text3: "Transporte Aeroporto / Hotel",
      description: "Quarto Deluxe com cama King-Size",
      daily: 4,
      oldPrice: "1.780,00",
      redColor: oldPriceTheme,
      price: "2.670,00",
      greenColor: priceTheme,
      app: "Só no APP"),
  Place(
      photo: "assets/images/foto5.jpg",
      name: "Hotel Acapulco",
      points: 9.9,
      extra1: FaIcon(FontAwesomeIcons.snowflake),
      text1: "Ambiente climatizado",
      extra2: FaIcon(FontAwesomeIcons.swimmingPool),
      text2: "Área de natação",
      extra3: FaIcon(FontAwesomeIcons.bus),
      text3: "Transporte Aeroporto / Hotel",
      description: "Linda área aberta com piscina e bar molhado",
      daily: 4,
      price: "2.790,00"),
];
